AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Requirement Orders functions.
Resources:
  requirementorder:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.requirementsOrders
      Runtime: nodejs8.10
      CodeUri: s3://sam-requirement-orders/1768a5b90968f5d259640f15be65b328
      Description: A simple backend with a RESTful API endpoint using Amazon API Gateway.
      MemorySize: 512
      Timeout: 10
      Policies:
      - Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - dynamodb:DeleteItem
          - dynamodb:GetItem
          - dynamodb:PutItem
          - dynamodb:UpdateItem
          - dynamodb:Scan
          Resource:
            Fn::Join:
            - ''
            - - 'arn:aws:dynamodb:'
              - Ref: AWS::Region
              - ':'
              - Ref: AWS::AccountId
              - :table/samRequirementOrder
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /requirementorder
            Method: POST
        Api2:
          Type: Api
          Properties:
            Path: /requirementorder
            Method: GET
        Api3:
          Type: Api
          Properties:
            Path: /requirementorder/{itemId}
            Method: ANY
  samRequirementOrder:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: samRequirementOrder
      AttributeDefinitions:
      - AttributeName: itemId
        AttributeType: S
      KeySchema:
      - AttributeName: itemId
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
